name: "Setup Python + uv (cached)"
description: "Sets up Python 3.12 and uv with sensible caching for GitHub CI and act"

runs:
  using: "composite"
  steps:
    - name: Setup Python 3.12
      if: ${{ always() && env.ACT }}
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        cache-dependency-glob: |
          uv.lock
          pyproject.toml
        cache-local-path: "${{ github.workspace }}/.uv-cache"

    - name: setup-uv notice (act only)
      if: ${{ always() && env.ACT }}
      shell: bash
      run: |
        echo "::group::[setup-uv] Tool versions";
        python --version || true;
        uv --version || true;
        echo "::endgroup::";
        echo "::group::[setup-uv] Environment";
        echo "HOME=$HOME";
        echo "GITHUB_WORKSPACE=${GITHUB_WORKSPACE}";
        echo "::endgroup::";
